server.port=8081
spring.application.name=service-product

spring.cloud.nacos.server-addr=127.0.0.1:8848
#???????????????????????
spring.cloud.nacos.config.import-check.enabled=false

# database
spring.datasource.url=jdbc:postgresql://localhost:5432/weifuwu2
spring.datasource.username=postgres
spring.datasource.password=451300
spring.datasource.driver-class-name=org.postgresql.Driver

# MyBatis
mybatis.mapper-locations=classpath:mapper/*.xml
mybatis.configuration.log-impl=org.apache.ibatis.logging.stdout.StdOutImpl
mybatis.configuration.mapUnderscoreToCamelCase=true

